name: Go

on:
  push:
    branches: [ master ]
    paths:
      - 'pkg/**'
      - 'solve/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'pkg/**'
      - 'solve/**'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@master
      with:
        go-version: 1.17
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt # optional
