name: Go

on:
  push:
    branches: [ master ]
    paths:
      - 'pkg/**'
      - 'solve/**'
      - '.github/workflows/go.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'pkg/**'
      - 'solve/**'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@master
      with:
        go-version: 1.19
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/cache@v3
      with:
        path: |
          ./bin
        key: ${{ runner.os }}-bin-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-bin
    - name: lint
      run: make lint

    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic ./...
    - uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt # optional
